Repository Schroedinger-Hat/schroedinger-hat-website, pull requests merged in 2023-12, with the labels that each got.

#102 [WIP]: Refactor events page
  .eslintrc
  package-lock.json
  package.json
  src/components/EventCard.vue
  src/components/buttons/CtaComponent.vue
  src/components/events/EventCard.vue
  src/components/events/EventForm.vue
  src/components/events/EventFormSelect.vue
  src/components/events/IconDetail.vue
  src/components/layout/TheNavbar.vue
  src/i18n/events/event/osday-21.json
  src/i18n/events/event/osday-23.json
  src/i18n/events/event/osday-24.json
  src/i18n/events/index.ts
  src/i18n/events/page.json
  src/i18n/events/session/florence1-06-23.json
  src/i18n/events/session/florence2-11-23.json
  src/i18n/events/session/milan1-23.json
  src/i18n/events/session/milan2-23.json
  src/i18n/events/session/verona1-23.json
  src/i18n/events/session/verona2-23.json
  src/i18n/events/session/verona3-23.json
  src/i18n/messages.ts
  src/pages/CodeConduct.vue
  src/pages/EventView.vue
  src/pages/PageEvents.vue
  src/pages/PageHome.vue
  src/pages/TeamMember.vue
  src/pages/TeamPage.vue
  src/router.ts
  src/views/EventList.vue
  tsconfig.json
  unocss.config.ts
  vite.config.ts
Labels: enhancement, urgent

#109 chore(deps): update dependencies, bump node version
  .eslintrc
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  .nvmrc
  README.md
  cypress/support/commands.ts
  cypress/support/e2e.ts
  eslint.config.js
  package-lock.json
  package.json
  schrodinger-hat-website.code-workspace
  src/components/buttons/CtaComponent.vue
  src/i18n/events/event/osday-23.json
  src/i18n/messages.ts
  src/pages/EventView.vue
  src/registerServiceWorker.ts
  tsconfig.json
Labels: chore

#110 feature: remove spotify button, implement OSDay button and banner
  src/App.vue
  src/components/buttons/CtaComponent.vue
  src/components/layout/MobileMenu.vue
  src/components/layout/TheBanner.vue
  src/functions/useBannerCookie.ts
  src/i18n/messages.ts
  src/pages/PageHome.vue
  src/styles/_variables.scss
  unocss.config.ts
Labels: enhancement

#113 docs(README): update node and npm values
  README.md
Labels: documentation

#112 refactor(templates): simplify issue and PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/pull_request_template.md
Labels: enhancement

#111 refactor(CtaIcon): reduce boilerplate, utilize Icon component
  src/components/buttons/CtaComponent.vue
  src/components/buttons/CtaIcon.vue
  src/components/layout/TheNavbar.vue
  src/styles/_variables.scss
  vite.config.ts
Labels: enhancement
